language: java
sudo: false
script: umask 0022 && mvn clean test
jdk:
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
